name: Fetch Prompts and Push
on:
  schedule:
    - cron: '0 * * * *' # 每小时执行一次
  workflow_dispatch:
jobs:
  fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Fetch prompts from API
        run: |
          # 设置更长的超时和更多重试
          max_retries=5
          retry_count=0
          success=false
          
          while [ $retry_count -lt $max_retries ]; do
            filename="prompts_$(date +%Y%m%d_%H%M%S).json"
            
            # 尝试下载，增加详细的错误日志
            echo "尝试下载 Prompts (第 $((retry_count + 1)) 次)"
            curl -v -sSL --retry 3 --retry-delay 10 --max-time 120 \
              -f "https://www.jasongjz.top/api/v1/prompts/?skip=0&limit=9000" | jq '.' > "$filename" 2>curl_error.log
            
            # 检查下载是否成功
            if [ -s "$filename" ] && jq empty "$filename" >/dev/null 2>&1; then
              success=true
              break
            else
              echo "下载失败，错误日志："
              cat curl_error.log
              retry_count=$((retry_count + 1))
              sleep 30  # 增加等待时间
            fi
          done
          
          # 如果所有重试都失败
          if [ "$success" = false ]; then
            echo "所有下载尝试都失败了"
            
            # 尝试查找最近的有效文件
            last_files=$(ls prompts_*.json 2>/dev/null | sort -r)
            for last_file in $last_files; do
              if [ -s "$last_file" ] && jq empty "$last_file" >/dev/null 2>&1; then
                echo "使用最近的有效文件: $last_file"
                cp "$last_file" "$filename"
                success=true
                break
              fi
            done
            
            # 如果仍然无法恢复
            if [ "$success" = false ]; then
              echo "无法恢复有效的 Prompts 文件"
              exit 1
            fi
          fi
          
          echo "$filename" > version.txt
          echo "Saved as $filename"
          echo "FILENAME=$filename" >> $GITHUB_ENV
      
      - name: Update README
        run: |
          # 使用从前一步骤传递的环境变量
          filename="$FILENAME"
          # 如果 README.md 中没有"当前版本："这一行，就追加
          if ! grep -q "## 当前版本：" README.md; then
            # 确保文件末尾有换行符，然后添加新行
            echo "" >> README.md
            echo "## 当前版本：[$filename](https://github.com/Larch-C/SavePrompt/blob/main/$filename)" >> README.md
          else
            # 使用 sed 替换包含"## 当前版本："的行
            sed -i "s/## 当前版本：.*$/## 当前版本：[$filename](https:\/\/github.com\/Larch-C\/SavePrompt\/blob\/main\/$filename)/" README.md
          fi
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'Larch-C'
          git config --global user.email 'tr@wenturc.com'
          git add prompts_*.json version.txt README.md
          git diff --cached --quiet && echo "No changes to commit" && exit 0
          git commit --author="IGCrystal <IGCrystal@wenturc.com>" -m "chore: add new prompts snapshot"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
