name: Fetch Prompts and Push

on:
  schedule:
    - cron: '0 * * * *' # 每小时执行一次
  workflow_dispatch:

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch prompts from API
        run: |
          filename="prompts_$(date +%Y%m%d_%H%M%S).json"
          curl -sSL "https://www.jasongjz.top/api/v1/prompts/?skip=0&limit=9000" | jq '.' > "$filename"
          echo "Saved as $filename"

      - name: Commit and push changes
        run: |
          git config --global user.name 'Larch-C'
          git config --global user.email 'tr@wenturc.com'
          git add prompts_*.json
          git diff --cached --quiet && echo "No changes to commit" && exit 0
          echo "chore: add new prompts snapshot\n\nCo-authored-by: Larch-C <tr@wenturc.com>\nCo-authored-by: IGCrystal <IGCrystal@wenturc.com>" > commitmsg.txt
          git commit -F commitmsg.txt
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
